spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15

#disable error log "StatusResource: Could not determine if the replica is available"
logging:
  level:
    com.netflix.eureka.resources: 'OFF'
