server:
  port: 0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://${master.ip:127.0.0.1}:8761/eureka/
spring:
  application:
    name: slave
  data:
    elasticsearch:
      cluster-nodes: ${master.ip:127.0.0.1}:9300
      repositories:
        enabled: true